### ISSUE TITLE
Unexpected emit for destroyed `OutputRef`. The owning directive/component is destroyed.

### ISSUE THREAD

**Issue by JustDoItSascha** [ngneat/helipopper#169]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

When you have a tooltip on a button and the click of the button will lead to a reroute of the page, then we get this error:

```
ERROR RuntimeError: NG0953: Unexpected emit for destroyed `OutputRef`. The owning directive/component is destroyed.
    at OutputEmitterRef.emit (core.mjs:6706:13)
    at getter.set (core.mjs:18681:18)
    at _TippyDirective.onHidden (ngneat-helipopper.mjs:592:20)
    at Object.onHidden (ngneat-helipopper.mjs:494:14)
    at invokeHook (tippy.esm.js:691:48)
    at Object.unmount (tippy.esm.js:1346:5)
    at Object.destroy (tippy.esm.js:1357:14)
    at ngneat-helipopper.mjs:329:22
    at processCleanups (core.mjs:11631:7)
    at cleanUpView (core.mjs:11568:5)
```

This happens in Angular 19 with the version `10.1.0-alpha.0`.

## Environment

<pre><code>
Angular version: 19.0.1
Helipopper version: 10.1.0-alpha.0

Browser:
- [x] Chrome (desktop) version

**Comment by JustDoItSascha** [comment]
P.S. It also happens in Helipopper version 9. So it has something to do with angular 19 i think.

**Comment by arturovt** [comment]
Can you provide a minimal reproducible example?

**Comment by JustDoItSascha** [comment]
@arturovt Sure, here: https://stackblitz.com/edit/stackblitz-starters-vkshhp?file=src%2Fapp%2Fcomponent-a%2Fcomponent-a.component.ts

**Comment by arturovt** [comment]
Thank you. I'll have a look shortly.

**Comment by arturovt** [comment]
I've published `10.2.0-alpha.0`.

**Comment by arturovt** [comment]
Because there was an Angular upgrade.
