### ISSUE TITLE
Error installing package in Angular v12

### ISSUE THREAD

**Issue by nip10** [ngneat/helipopper#55]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

Can't install the package because the installation command 
```
ng add @ngneat/helipopper
```
fails with an error.

Error log:
<pre><code>
λ ng add @ngneat/helipopper
i Using package manager: npm
√ Found compatible package version: @ngneat/helipopper@3.6.0.
√ Package information loaded.

The package @ngneat/helipopper@3.6.0 will be installed and executed.
Would you like to proceed? Yes
√ Package successfully installed.
"SchematicsHelipopperAdd" schema is using the keyword "id" which its support is deprecated. Use "$id" for schema ID.
Cannot read property 'defaultProject' of undefined
</code></pre>

After the `ng add` script running, the `@ngneat/helipopper` package is added to package.json.
If I try to run the project using `npm start`, I get a deps error:

<pre><code>
C:\dev\redacted-web\node_modules\@angular\compiler-cli\ngcc\src\entry_point_finder\targeted_entry_point_finder.js:40
                throw new Error("The target entry-point \"" + invalidTarget.entryPoint.name + "\" has missing dependencies:\n" +
                ^

Error: The target entry-point "@ngneat/helipopper" has missing dependencies:
 - @ngneat/overview

    at TargetedEntryPointFinder.findEntryPoints (C:\dev\redacted-web\node_modules\@angular\compiler-cli\ngcc\src\entry_point_finder\targeted_entry_point_finder.js:40:23)
    at C:\dev\redacted-web\node_modules\@angular\compiler-cli\ngcc\src\execution\analyze_entry_points.js:29:41
    at SingleProcessExecutorSync.SingleProcessorExecutorBase.doExecute (C:\dev\redacted-web\node_modules\@angular\compiler-cli\ngcc\src\execution\single_process_executor.js:28:29)
    at C:\dev\redacted-web\node_modules\@angular\compiler-cli\ngcc\src\execution\single_process_executor.js:57:59
    at SyncLocker.lock (C:\dev\redacted-web\node_modules\@angular\compiler-cli\ngcc\src\locking\sync_locker.js:34:24)
    at SingleProcessExecutorSync.execute (C:\dev\redacted-web\node_modules\@angular\compiler-cli\ngcc\src\execution\single_process_executor.js:57:27)
    at Object.mainNgcc (C:\dev\redacted-web\node_modules\@angular\compiler-cli\ngcc\src\main.js:74:25)
    at Object.process (C:\dev\redacted-web\node_modules\@angular\compiler-cli\ngcc\index.js:29:23)
    at NgccProcessor.processModule (C:\dev\redacted-web\node_modules\@ngtools\webpack\src\ngcc_processor.js:164:16)
    at C:\dev\redacted-web\node_modules\@ngtools\webpack\src\ivy\host.js:128:18
    at C:\dev\redacted-web\node_modules\@ngtools\webpack\src\ivy\host.js:58:24
    at Array.map (<anonymous>)
    at Object.host.resolveModuleNames (C:\dev\redacted-web\node_modules\@ngtools\webpack\src\ivy\host.js:56:32)
    at actualResolveModuleNamesWorker (C:\dev\redacted-web\node_modules\typescript\lib\typescript.js:106560:133)
    at resolveModuleNamesWorker (C:\dev\redacted-web\node_modules\typescript\lib\typescript.js:106810:26)
    at resolveModuleNamesReusingOldState (C:\dev\redacted-web\node_modules\typescript\lib\typescript.js:106907:24)
</code></pre>

Notes:
- The `Cannot read property 'defaultProject' of undefined` error seems to come from [here](https://github.com/ngneat/helipopper/blob/254cfbb47852d60c4c6fb4c78ef7e8a90f8d5905/schematics/src/utils/projects.ts#L24).
- The workaround is to manually install `@ngneat/overview` 

## Expected behavior

Package should be installed successfully,

## Minimal reproduction of the problem with instructions

1. Create new Angular v12 project using `ng new tooltiptest`
2. Run `ng add @ngneat/helipopper`

## What is the motivation / use case for changing the behavior?

To be able to use this package.

## Environment

<pre><code>
Angular CLI: 12.0.5
Node: 14.16.1
Package Manager: npm 7.12.0
OS: win32 ia32

Angular: 12.0.5
... animations, cli, common, compiler, compiler-cli, core
... elements, forms, google-maps, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.5
@angular-devkit/build-angular   12.0.5
@angular-devkit/core            12.0.5
@angular-devkit/schematics      12.0.5
@schematics/angular             12.0.5
rxjs                            6.6.7
typescript                      4.2.4
</code></pre>

**Comment by NetanelBasal** [comment]
We need to upgrade to v12
